volumes:
  postgres_data: {}
services:
  postgres:
    image: docker.io/library/postgres:18
    env_file:
    - postgres.env
    volumes:
    - postgres_data:/var/lib/postgresql/18/docker:delegated
    command:
    - postgres
    - -c
    - shared_preload_libraries=pg_stat_statements
  aidbox:
    image: docker.io/healthsamurai/aidboxone:edge
    env_file:
    - aidbox.env
    pull_policy: always
    depends_on:
    - postgres
    ports:
    - 8080:8080
    healthcheck:
      test: curl -f http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 90
      start_period: 30s
